Repository andela/riders-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#1 #165413095 setup unit testing
  .babelrc
  .gitignore
  app.js
  index.js
  package-lock.json
  package.json
  tests/test.js
Labels: peer review

#4 #165413090 Setup Travis CI for management service
  .travis.yml
  README.md
Labels: TTL review

#7 #165595055 added nodemon
  app.js
  package-lock.json
  package.json
Labels: TTL review

#5 #165413097 Setup Api Documentation
  .env.sample
  .gitignore
  app.js
  config/index.js
  config/passport.js
  config/swagger.js
  index.js
  models/User.js
  package.json
  routes/api/index.js
  routes/api/users.js
  routes/index.js
  tests/test.js
Labels: WIP

#8 #165413091 configure PostgreSQL as a db engine
  .env.sample
  .gitignore
  .sequelizerc
  config/config.js
  index.js
  migrations/20190425110658-create-users.js
  models/User.js
  models/index.js
  models/users.js
  package.json
Labels: TTL review
