Repository andela/riders-ah-backend, pull requests merged in 2019-05, with the labels that each got.

#6 #165413096 Integrate with coveralls
  .gitignore
  .travis.yml
  README.md
  package.json
Labels: Finished, TTL review

#13 #165413104 Enable Social Login via Google, Facebook and twitter
  .babelrc
  .env.sample
  config/passport.js
  config/passport/index.js
  config/passport/strategy.js
  config/passport/testStrategy.js
  controllers/user.controller.js
  helpers/TestStrategy.js
  helpers/index.js
  helpers/mockUser.js
  helpers/passport.js
  migrations/20190425110658-create-users.js
  models/users.js
  package.json
  routes/api/auth.js
  routes/api/index.js
  routes/index.js
  tests/social-login-test.js
Labels: Finished, TTL review

#11 #165413099 intergrate jwt
  .travis.yml
  app.js
  config/passport/localstrategy.js
  controllers/user.controller.js
  middlewares/auth.js
  middlewares/index.js
  migrations/20190425110658-create-users.js
  models/users.js
  routes/api/auth/auth.js
  routes/api/auth/doc.js
  routes/api/auth/users.js
  routes/api/index.js
  routes/api/users.js
  tests/user.test.js
Labels: Finished, TTL review

#10 #165413094 Add heroku app.json Documentation
  .gitignore
  app.json
  config/swagger.js
Labels: WIP

#16 #165830902 Fix coverage
  README.md
Labels: peer review

#12 #165413100 Create a function to send an email
  .env.sample
  helpers/index.js
  helpers/utils/mail-sender.js
  package.json
  tests/mail-sender-test.js
Labels: TTL review

#14 #165413103 reset password via email
  .eslintrc.json
  .hound.yml
  .sequelizerc
  config/config.js
  config/swagger.js
  controllers/resetPassword.js
  middlewares/auth.js
  migrations/20190425110658-create-users.js
  models/index.js
  package.json
  routes/api/index.js
  routes/api/resetPassword/doc.js
  routes/api/resetPassword/resetPassword.js
  tests/resetPasswordTest.js
Labels: TTL review

#17 #165413106 Create article
  controllers/article.controller.js
  helpers/article.js
  migrations/20190507072245-create-article.js
  migrations/20190507232509-add-associations.js
  models/article.js
  models/users.js
  package.json
  routes/api/article/articles.js
  routes/api/auth/auth.js
  routes/api/auth/doc.js
  routes/api/index.js
  tests/article.test.js
  tests/profile.js
Labels: TTL review, peer review

#18 #16541310 Validate user registration
  config/passport/localstrategy.js
  controllers/user.controller.js
  helpers/index.js
  helpers/userHelper.js
  routes/api/auth/doc.js
  routes/api/auth/users.js
  tests/article.test.js
  tests/user.test.js
Labels: peer review

#24 bug(social):Fix a bug in twitter login
  app.js
Labels: Finished

#22 #16541310 Users should be able to give a rating to an article
  controllers/rating.controller.js
  helpers/articleRatevalidator.js
  middlewares/article.js
  migrations/20190507072245-create-article.js
  migrations/20190508204409-create-rating.js
  models/article.js
  models/rating.js
  models/users.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  routes/api/article/rating.js
  tests/rate-article.test.js
Labels: peer review

#20 #165413126 role based access
  app.js
  controllers/roles.js
  helpers/accessServices.js
  helpers/roles.js
  middlewares/roles.js
  migrations/20190425110658-create-users.js
  models/users.js
  routes/api/index.js
  routes/api/roles/doc.js
  routes/api/roles/roles.js
  tests/role-based-access.js
Labels: TTL review

#25 #165965800 remove user data on signup response
  controllers/user.controller.js
  tests/rate-article.test.js
  tests/user.test.js
Labels: Finished, TTL review

#21 #165413111 allow user to comment on an article
  controllers/comment.controller.js
  helpers/commentHelper.js
  migrations/20190507072245-create-article.js
  migrations/20190508132500-create-comment.js
  models/article.js
  models/comment.js
  models/users.js
  routes/api/comment/comment.js
  routes/api/comment/doc.js
  routes/api/index.js
  tests/comment.test.js
Labels: TTL review

#26 #165413111 user is able to like and dislike an article
  controllers/article.controller.js
  helpers/article.js
  migrations/20190512132342-create-like.js
  models/article.js
  models/like.js
  models/users.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  routes/api/resetPassword/doc.js
  tests/like.dislike.test.js
Labels: TTL review

#27 #165413114 Users should be able to receive notifications
  app.js
  controllers/article.controller.js
  controllers/notification.controller.js
  helpers/article.js
  helpers/eventEmitters.js
  helpers/notification.js
  helpers/notificationEvent.js
  helpers/utils/eventHandlers.js
  migrations/20190425110658-create-users.js
  migrations/20190510082118-create-follow.js
  migrations/20190511120555-create-notification.js
  models/follow.js
  models/notification.js
  models/users.js
  package.json
  routes/api/auth/doc.js
  routes/api/auth/notification.js
  routes/api/index.js
  tests/notification.test.js
Labels: TTL review

#19 #165413115 Tag article
  controllers/article.controller.js
  helpers/article.js
  helpers/tag.helper.js
  middlewares/tag.middleware.js
  migrations/20190508141022-create-tag.js
  models/article.js
  models/tag.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  routes/api/index.js
  routes/index.js
  tests/tag.test.js
Labels: TTL review, peer review

#31 #165965800 rating using article slug instead of article id
  controllers/rating.controller.js
  helpers/articleRatevalidator.js
  middlewares/article.js
  migrations/20190508204409-create-rating.js
  models/article.js
  models/rating.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  routes/api/article/rating.js
  tests/rate-article.test.js
Labels: TTL review

#23 #165413113 Follow and/or unfollow user
  controllers/profile.js
  helpers/notification.js
  helpers/notificationEvent.js
  helpers/user.helper.js
  middlewares/user.middleware.js
  models/users.js
  routes/api/profile/doc.js
  routes/api/profile/follow.js
  routes/api/profile/profile.js
  tests/follow.test.js
Labels: TTL review

#34 #165413117 Get list of users
  controllers/user.controller.js
  helpers/userHelper.js
  routes/api/auth/doc.js
  routes/api/auth/users.js
  tests/list.users.test.js
Labels: peer review

#35 #165413120 user share article
  controllers/article.controller.js
  helpers/article.js
  migrations/20190518093044-create-share.js
  models/article.js
  models/share.js
  models/users.js
  package.json
  routes/api/article/articles.js
  routes/api/article/doc.js
  tests/share.test.js
Labels: peer review

#37 #165413108 fetch all ratings related to an article
  controllers/rating.controller.js
  helpers/articleRatevalidator.js
  models/rating.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  tests/rate-article.test.js
Labels: peer review

#40 #165413109 pagination for article ratings
  helpers/articleRatevalidator.js
  tests/rate-article.test.js
Labels: peer review

#38 #165413121 user can bookmark article to read later
  controllers/article.controller.js
  helpers/article.js
  migrations/20190518210158-create-bookmark.js
  models/article.js
  models/bookmark.js
  models/like.js
  models/users.js
  routes/api/article/articles.js
  routes/api/article/doc.js
  tests/bookmark.test.js
Labels: peer review

#45 #166176663 Update packages
  helpers/index.js
  package.json
Labels: peer review

#32 #165413123 Users should be able to like a specific comment
  controllers/comment.controller.js
  helpers/commentHelper.js
  migrations/20190517181756-create-comment-feedback.js
  models/comment.js
  models/commentfeedback.js
  models/users.js
  routes/api/comment/comment.js
  routes/api/comment/doc.js
  routes/api/comment/like.js
  routes/api/index.js
  tests/comment.test.js
Labels: TTL review

#44 #165413124 Get articles reading stats
  controllers/article.controller.js
  controllers/read.stats.controller.js
  helpers/read.stats.helper.js
  helpers/userHelper.js
  migrations/20190425110658-create-users.js
  migrations/20190521075408-create-reading-stat.js
  models/article.js
  models/readingstat.js
  models/users.js
  routes/api/article/articles.js
  routes/api/index.js
  routes/api/user/user.route.js
  tests/read.stats.test.js
Labels: peer review

#41 #166160563 Replace rate to ratings on ratings endpoints URL
  routes/api/article/articles.js
  tests/rate-article.test.js
Labels: peer review

#51 #165413128 Tracking comment edits
  controllers/comment.controller.js
  helpers/commentHelper.js
  middlewares/catch.errors.middleware.js
  migrations/20190526205547-create-comment-history.js
  models/comment.js
  models/commenthistory.js
  models/index.js
  routes/api/comment/comment.js
  tests/comment.test.js
Labels: peer review

#49 #165413052 Add basic chat feature
  app.js
  controllers/message.controller.js
  helpers/messageHelper.js
  helpers/utils/eventHandlers.js
  helpers/utils/socketIo.js
  html/chat.html
  index.js
  migrations/20190523121002-create-message.js
  models/message.js
  models/users.js
  package.json
  routes/api/index.js
  routes/api/message/doc.js
  routes/api/message/message.js
  tests/chats.test.js
Labels: peer review
